language: python
python:
  - "3.3"
  - "3.4"
env:
  - BUP_TESTS=$TRAVIS_BUILD_DIR/src/barsup/tests
install:
  - pip install -r REQUIREMENTS
  - pip install pytest pytest-cov coveralls


# command to run tests
script:
  - py.test --pep8 --cov .

after_success:
  - coveralls