language: python
python:
- '3.3'
- '3.4'
install:
- easy_install -U pip routes
- pip install -r REQUIREMENTS.test
script:
- pep257 ./
- py.test --pep8 --cov ./src --cov-config=.coveragerc
after_success:
- coveralls
notifications:
  hipchat:
    rooms:
      - b7098c17bc3283dc7ca388b68e3ca3@barsup
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'
deploy:
  provider: pypi
  user: bars-travis
  password:
    secure: C8KHE81/HnOoLZcYW3DuqLPR4ovvAqN2l3Wr4lCujUnjFqhnXb33+Mz+JumfdNFbqz6JSAihpkU0xA0VQ+ox1I7LnP8e7wSUWURqfePH3b0Y4fX7LbK0ehWcsdlkHmxNfzc6VIEN8CQkXnfuy6Uj27NtRSkbgHJWBFGb9yHvz+U=
  on:
    tags: true
    all_branches: true
  distributions: bdist_wheel