language: python
python:
- '3.3'
- '3.4'
install:
- easy_install -U pip routes
- pip install -r REQUIREMENTS.test
- export BUP_TESTS=$TRAVIS_BUILD_DIR/src/barsup/tests
- export BUP_PATH=$TRAVIS_BUILD_DIR/src/barsup/tests/wsgi
- export BUP_CONFIG=$TRAVIS_BUILD_DIR/src/barsup/tests/wsgi/container.json
script:
- py.test --pep8 --cov ./src --cov-config=.coveragerc
after_success:
- coveralls
notifications:
  email:
    recipients:
    - telepenin@bars-open.ru
    - pirogov@bars-open.ru
deploy:
  provider: pypi
  user: bars-travis
  password:
    secure: C8KHE81/HnOoLZcYW3DuqLPR4ovvAqN2l3Wr4lCujUnjFqhnXb33+Mz+JumfdNFbqz6JSAihpkU0xA0VQ+ox1I7LnP8e7wSUWURqfePH3b0Y4fX7LbK0ehWcsdlkHmxNfzc6VIEN8CQkXnfuy6Uj27NtRSkbgHJWBFGb9yHvz+U=
  on:
    tags: true
    all_branches: true
  distributions: "sdist bdist_wheel"