language: python
python:
  - "3.3"
  - "3.4"
env:
  - BUP_TESTS=$TRAVIS_BUILD_DIR/src/barsup/tests
install:
  - easy_install -U pip
  - easy_install routes
  - pip install -r REQUIREMENTS.test

script:
  - py.test --pep8 --cov ./ --cov-config=.coveragerc

after_success:
  - coveralls