language: python
python:
  - "3.3"
  - "3.4"
env:
  - BUP_TESTS=$TRAVIS_BUILD_DIR/src/barsup/tests
install:
  - pip install pytest pytest-cov coveralls
  - pip install -r REQUIREMENTS

# command to run tests
script: python -m pytest