language: python
python:
  - "3.3"
  - "3.4"

install:
  - easy_install -U pip
  - pip install -r REQUIREMENTS.test

script:
  - py.test --pep8 --cov $TRAVIS_BUILD_DIR/src/barsup/tests

after_success:
  - coveralls