language: python
python:
  - "3.3"
  - "3.4"
env:
  - BUP_TESTS=$TRAVIS_BUILD_DIR/src/barsup/tests
install:
  - easy_install -U pip

  # иначе переодически вылетает routes is in an unsupported or invalid wheel
  - easy_install routes

  - pip install -r REQUIREMENTS.test


# command to run tests
script:
  - py.test --pep8 --cov ./

after_success:
  - coveralls